from __future__ import annotations

from pathlib import Path
import unittest

from aha_cli.web.http_utils import static_response


class FrontendStaticTests(unittest.TestCase):
    def test_frontend_prefers_websocket_with_cursor_and_polling_fallback(self) -> None:
        script_path = Path(__file__).resolve().parents[1] / "src" / "aha_cli" / "web" / "static" / "app.js"
        script = script_path.read_text(encoding="utf-8")
        websocket_index = script.find("new WebSocket")

        self.assertGreaterEqual(websocket_index, 0, "frontend should open a WebSocket transport")
        websocket_block = script[max(0, websocket_index - 2000) : websocket_index + 3000]
        self.assertRegex(script, r"last_event_id|after_event_id")
        self.assertRegex(websocket_block, r"onclose|onerror|catch")
        self.assertIn("pollEvents", script)
        self.assertIn("catchUpRealtimeEvents", script)
        self.assertIn("forcePoll", script)
        self.assertIn("allowStalePoll", script)
        self.assertIn("lastRealtimeMessageAt", script)
        self.assertIn("eventSocketStaleMs", script)
        self.assertIn("closeStaleEventWebSocket", script)
        self.assertIn("ws.stale_close", script)
        self.assertIn("visibilitychange", script)
        self.assertIn('"online"', script)
        self.assertRegex(script, r"typeof\s+WebSocket|WebSocket\s+in\s+window|window\.WebSocket")

    def test_frontend_uses_bootstrap_for_empty_state(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "src" / "aha_cli" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("/api/bootstrap", script)
        self.assertIn('fetchJson(apiUrl("/api/tasks", params)', script)
        self.assertIn('apiUrl("/api/agents/runtime"', script)
        self.assertIn("agentsRuntimeCache", script)
        self.assertIn("renderFirstRunState", script)
        self.assertIn("renderBootstrapConfigState", script)
        self.assertIn('id="aha-settings"', html)
        self.assertIn('id="settings-dialog"', html)
        self.assertIn("initSettingsDialog", script)
        self.assertIn('data-bootstrap-config-mode="${escapeHtml(mode)}"', script)
        self.assertIn('bootstrapConfigFormHtml({ mode: "settings"', script)
        self.assertIn("body.force = true", script)
        self.assertIn("data-bootstrap-config-form", script)
        self.assertIn("data-bootstrap-config-field", script)
        self.assertIn("Core Settings", script)
        self.assertIn("Task concurrency", script)
        self.assertIn("Active env group", script)
        self.assertIn('data-bootstrap-config-field="claude.env_active"', script)
        self.assertIn("data-bootstrap-env-name", script)
        self.assertIn("data-bootstrap-env-field", script)
        self.assertIn("ANTHROPIC_BASE_URL", script)
        self.assertIn("ANTHROPIC_MODEL", script)
        self.assertIn("ANTHROPIC_API_KEY", script)
        self.assertNotIn("data-bootstrap-env-key", script)
        self.assertNotIn("data-bootstrap-env-active", script)
        self.assertNotIn("data-bootstrap-context-tokens", script)
        self.assertNotIn('data-bootstrap-config-field="runner_command"', script)
        self.assertNotIn('data-bootstrap-config-field="default_mode"', script)
        self.assertNotIn('data-bootstrap-config-field="claude.model"', script)
        self.assertNotIn("Default Claude model", script)
        self.assertNotIn("task-env-model", html)
        self.assertNotIn("task-env-model", styles)
        self.assertIn("Claude official (no env)", script)
        self.assertIn('hasOwnProperty.call(claude, "env_active")', script)
        self.assertIn("activeClaudeEnvConfigured", script)
        self.assertIn("activeClaudeEnvModelLabel", script)
        self.assertIn("taskModelSelectionEnabled", script)
        self.assertIn('return configString(group.ANTHROPIC_MODEL, "not configured");', script)
        self.assertIn("if (taskModelSelectionEnabled()) payload.model", script)
        self.assertIn("taskBackendConfirmLabel", script)
        self.assertIn("Save AHA Config", script)
        self.assertIn("data-bootstrap-run-form", script)
        self.assertIn("createRunFromBootstrapForm", script)
        self.assertIn("data-bootstrap-run-name", script)
        self.assertIn("Run name", script)
        self.assertIn("Create Run", script)
        self.assertIn("runHasNoTasks", script)
        self.assertIn("Create first task", script)
        self.assertIn("data-open-first-task", script)
        self.assertIn("create_initial_task: createInitialTask", script)
        self.assertIn("createInitialTask: false", script)
        self.assertNotIn("data-bootstrap-run-mode", script)
        self.assertNotIn("data-bootstrap-collaboration-mode", script)
        self.assertNotIn("data-bootstrap-proxy-enabled", script)
        self.assertNotIn("data-bootstrap-http-proxy", script)
        self.assertNotIn("Start Run and Initial Task", script)
        self.assertNotIn("new-run-mode", html)
        self.assertNotIn("new-run-collaboration", html)
        self.assertIn("renderBootstrapError", script)
        self.assertNotIn("syncBootstrapCollaborationHelp", script)
        self.assertIn("body.empty-run .sidebar", styles)
        self.assertIn("bootstrap-panel", styles)
        self.assertIn("bootstrap-config-grid", styles)
        self.assertIn("bootstrap-config-stack", styles)
        self.assertIn("bootstrap-config-list", styles)
        self.assertIn("bootstrap-config-section", styles)
        self.assertIn("bootstrap-env-fields", styles)
        self.assertIn("first-task-empty", styles)
        self.assertIn("settings-dialog", styles)
        self.assertNotIn("bootstrap-context-row", styles)
        self.assertIn("bootstrap-proxy", styles)
        self.assertIn("collaboration-help", styles)

    def test_web_restart_polling_starts_quickly(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        restart_block = script[
            script.index("async function waitForWebRestartAndReload") : script.index("async function refreshAfterWebRestart")
        ]
        refresh_block = script[
            script.index("async function refreshAfterWebRestart") : script.index("function closeTaskCreateDialog")
        ]

        self.assertIn('async function waitForWebRestartAndReload(restartVersion = "")', script)
        self.assertIn("await sleep(500);", script)
        self.assertNotIn("await sleep(2500);", script)
        self.assertIn("const restartVersion = currentAppVersion();", script)
        self.assertIn('apiUrl("/api/bootstrap")', restart_block)
        self.assertNotIn('apiUrl("/api/status")', restart_block)
        self.assertIn("applyBootstrapPayload(payload);", restart_block)
        self.assertIn("if (nextVersion && nextVersion !== restartVersion)", script)
        self.assertNotIn("restartVersion && nextVersion && nextVersion !== restartVersion", script)
        self.assertNotIn("if (response.ok) {\n        window.location.reload();", script)
        self.assertIn("function applyBootstrapPayload", script)
        self.assertIn("await loadStatus({ forceAgents: true });", refresh_block)
        self.assertNotIn("await loadBackendStatus();", refresh_block)
        self.assertIn("function resetEventWebSocketReconnectState", script)
        self.assertIn("eventSocketFailureCount = 0;", script)
        self.assertIn("eventSocketReconnectAt = 0;", script)
        self.assertIn('resetEventWebSocketReconnectState("web_restart_recovered");', script)
        self.assertIn("await catchUpRealtimeEvents();", refresh_block)
        self.assertIn("await ensureEventWebSocket();", restart_block)
        self.assertIn("void refreshAfterWebRestart();", restart_block)
        self.assertIn('setWebRestartState("重启完成。");', script)

    def test_frontend_has_aha_logo_and_favicon(self) -> None:
        root = Path(__file__).resolve().parents[1]
        static_root = root / "src" / "aha_cli" / "web" / "static"
        html = (static_root / "index.html").read_text(encoding="utf-8")
        styles = (static_root / "styles.css").read_text(encoding="utf-8")
        logo = (static_root / "aha-logo.svg").read_text(encoding="utf-8")
        favicon = (static_root / "aha-favicon.svg").read_text(encoding="utf-8")
        logo_response = static_response("aha-logo.svg", "GET")
        favicon_response = static_response("aha-favicon.svg", "GET")

        self.assertIn("<title>AHA Dashboard</title>", html)
        self.assertIn('<link rel="icon" href="/static/aha-favicon.svg" type="image/svg+xml">', html)
        self.assertIn('class="brand-title"', html)
        self.assertIn('class="brand-logo" src="/static/aha-logo.svg"', html)
        self.assertIn('id="app-version"', html)
        self.assertNotIn('class="brand-full"', html)
        self.assertNotIn("<span class=\"brand-full\"> Dashboard</span>", html)
        self.assertIn(".brand-title", styles)
        self.assertIn(".brand-logo", styles)
        self.assertIn(".brand-short", styles)
        self.assertIn(".app-version", styles)
        self.assertIn("appVersionEl", (static_root / "app.js").read_text(encoding="utf-8"))
        self.assertIn("statusData?.aha_version", (static_root / "app.js").read_text(encoding="utf-8"))
        self.assertIn("max-width: min(34vw, 360px);", styles)
        self.assertIn("<title>AHA</title>", logo)
        self.assertIn("<title>AHA</title>", favicon)
        self.assertIn('viewBox="0 0 64 64"', logo)
        self.assertIn('viewBox="0 0 64 64"', favicon)
        self.assertIn(b"Content-Type: image/svg+xml", logo_response)
        self.assertIn(b"Content-Type: image/svg+xml", favicon_response)

    def test_frontend_confirms_task_final_and_hide(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn('action === "hide" && !confirm(`Hide ${taskId} from the task list?\\n\\nYou can restore hidden tasks later.`)', script)
        self.assertIn('(action === "final" || action === "complete") && !confirm(`Ask task-main to generate the Final for ${taskId}?`)', script)

    def test_frontend_has_play_console_entry(self) -> None:
        root = Path(__file__).resolve().parents[1]
        static_root = root / "src" / "aha_cli" / "web" / "static"
        html = (static_root / "index.html").read_text(encoding="utf-8")
        script = (static_root / "app.js").read_text(encoding="utf-8")
        styles = (static_root / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="play-console"', html)
        self.assertIn('id="play-console-popover"', html)
        self.assertIn('id="web-service-address"', html)
        self.assertIn("玩了个玩", html)
        actions_start = html.find('<div class="web-service-actions">')
        actions_end = html.find('<div id="play-console-popover"', actions_start)
        session_detail = html.find('<div id="session-detail"')
        self.assertGreater(actions_start, -1)
        self.assertGreater(actions_end, actions_start)
        self.assertGreater(session_detail, actions_end)
        self.assertNotIn("0.0.0.0:8766", html[actions_start:actions_end])
        self.assertLess(html.find('id="session-detail-text"'), html.find('id="web-service-address"'))
        self.assertLess(html.find('id="web-service-address"'), html.find('id="run-id"'))
        self.assertIn("function renderPlayConsole()", script)
        self.assertIn('apiUrl("/api/games")', script)
        self.assertIn("playConsoleState", script)
        self.assertIn('runStateEl.textContent = "";', script)
        self.assertNotIn('const runStateText = `updated ${formatLocalTimestamp(updatedAt, updatedAt || "-")}`;', script)
        self.assertNotIn('updatedAt ? `更新 ${formatLocalTimestamp(updatedAt, updatedAt)}` : "",', script)
        self.assertIn("webgame_workspace", script)
        self.assertNotIn('href="/games/cailegecai/"', script)
        self.assertNotIn("task-056", script)
        self.assertIn("setPlayConsoleOpen", script)
        self.assertIn(".play-console-popover", styles)
        self.assertIn(".play-game-card", styles)
        self.assertNotIn(".web-service-actions code", styles)

    def test_frontend_composer_supports_multiline_input(self) -> None:
        root = Path(__file__).resolve().parents[1]
        static_root = root / "src" / "aha_cli" / "web" / "static"
        html = (static_root / "index.html").read_text(encoding="utf-8")
        script = (static_root / "app.js").read_text(encoding="utf-8")
        styles = (static_root / "styles.css").read_text(encoding="utf-8")

        self.assertIn('<textarea id="message" rows="1"', html)
        self.assertIn('enterkeyhint="enter"', html)
        self.assertNotIn('<input id="message"', html)
        self.assertIn("function syncMessageInputHeight()", script)
        self.assertIn("function composerPlainEnterCreatesNewline()", script)
        self.assertIn('window.matchMedia?.("(pointer: coarse)")', script)
        self.assertIn("navigator.maxTouchPoints", script)
        self.assertIn("if (event.isComposing || event.keyCode === 229) return;", script)
        self.assertIn('const plainEnter = event.key === "Enter" && !event.shiftKey', script)
        self.assertIn("const plainEnterSubmits = plainEnter && !composerPlainEnterCreatesNewline();", script)
        self.assertIn("requestComposerSubmit();", script)
        self.assertIn("function requestComposerSubmitFromPointer(event)", script)
        self.assertIn("composerPointerSubmitUntil = Date.now() + 500;", script)
        self.assertIn("function setComposerSubmitBusy(busy)", script)
        self.assertIn("if (composerSubmitInFlight) return;", script)
        self.assertIn("messageEl.value = \"\";", script)
        self.assertIn("messageEl.value = originalMessage;", script)
        self.assertIn('sendFormEl.querySelector("button.send")?.addEventListener("pointerdown"', script)
        self.assertIn(".composer textarea#message", styles)
        self.assertIn("max-height: 160px;", styles)

    def test_frontend_uses_modal_for_task_create(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "src" / "aha_cli" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("open-task-create", html)
        self.assertIn("task-create-dialog", html)
        self.assertIn("agent-runtime-confirm", html)
        self.assertIn("Save & restart backend", html)
        self.assertIn('id="weixin-console-popover" class="weixin-console-popover" hidden></div>\n        <select id="run-select"', html)
        self.assertIn("run-rename-form", html)
        self.assertIn("rename-run-name", html)
        self.assertIn("new-task-description", html)
        self.assertIn('form id="task-form"', html)
        self.assertIn("task-supervision-editor", html)
        self.assertIn("task-context-editor", html)
        self.assertIn("collaboration-mode", html)
        self.assertIn("collaboration-mode-help", html)
        self.assertIn("只限制 auto 模式下最多能启用几个 sub-agent", html)
        self.assertIn("selected-task-supervision-mode", html)
        self.assertIn("task-supervision-mode", html)
        self.assertIn("task-supervision-max-rounds", html)
        self.assertIn('id="task-supervision-max-rounds" type="number" min="1" max="100" value="99"', html)
        self.assertIn('id="selected-task-supervision-max-rounds" type="number" min="1" max="100" value="99"', html)
        self.assertIn('<option value="danger-full-access" selected>danger-full-access</option>', html)
        self.assertIn("task-supervision-ask-user-gates", html)
        self.assertIn("selected-task-supervision-ask-user-gates", html)
        self.assertIn("selected-task-context-auto-compact-enabled", html)
        self.assertIn('id="selected-task-context-threshold" type="number" min="1" max="99" value="75"', html)
        self.assertIn("assisted Codex host", html)
        self.assertIn("assisted Claude host", html)
        self.assertNotIn("selected-task-supervision-actions", html)
        create_form = html.split('<form id="task-form"', 1)[1].split("</form>", 1)[0]
        self.assertIn("task-supervision-mode", create_form)
        self.assertNotIn("selected-task-supervision-mode", create_form)
        self.assertIn("openTaskCreateDialog", script)
        self.assertIn("closeTaskCreateDialog", script)
        self.assertIn("renameCurrentRun", script)
        self.assertIn('method: "PATCH"', script)
        self.assertIn("renameRunNameEl", script)
        self.assertIn("syncCurrentRunDisplay(run, trimmedName);", script)
        self.assertIn("if (summaryEl && runName) summaryEl.textContent = runName;", script)
        self.assertIn("saveTaskSupervisionConfig", script)
        self.assertIn("saveTaskContextConfig", script)
        self.assertIn("syncTaskContextFields", script)
        self.assertIn("taskContextManagementPolicy", script)
        self.assertIn("const defaultTaskContextThresholdPercent = 75;", script)
        self.assertIn("context_management", script)
        self.assertIn("taskSupervisionPayloadFromMode", script)
        self.assertIn("collaboration_mode", script)
        self.assertIn("taskCollaborationSummary", script)
        self.assertIn("syncCollaborationFields", script)
        self.assertIn("collaborationModeDescriptions", script)
        self.assertIn("AHA 会在能提速时自动组队", script)
        self.assertIn("supervisionAskUserGateDefs", script)
        self.assertIn("const defaultTaskSupervisionMaxRounds = 99;", script)
        self.assertIn("supervisionAskUserGateDefs.map(([key]) => [key, false])", script)
        self.assertIn("ask_user_gates", script)
        self.assertIn("readAskUserGateControls", script)
        self.assertIn("syncCreateTaskSupervisionModeFields", script)
        self.assertIn("assisted_codex", script)
        self.assertIn('policy.mode === "manual"', script)
        self.assertIn('"host / user proxy"', script)
        self.assertIn("isSupervisionAgent", script)
        self.assertIn("Main & sub agents", script)
        self.assertIn("Supervision", script)
        self.assertIn("agent-section", script)
        self.assertIn("data-agent-id", script)
        self.assertIn('data-agent-field="backend"', script)
        self.assertIn("agentBackendOptions", script)
        self.assertIn("agent_backend_switched", script)
        self.assertIn("requestAgentRuntimeConfigAction", script)
        self.assertIn("restart_backend", script)
        self.assertIn("Save for next start keeps the process running.", script)
        self.assertIn("确认将 ${agent.id} backend", script)
        self.assertIn("setAgentConfigControlValue(target, previousBackend);", script)
        self.assertIn("host-agent", script)
        self.assertIn("display_sender", script)
        self.assertIn("from-supervision", script)
        self.assertIn("consumedAgentMessages", script)
        self.assertIn("mirroredMainBrowserMessages", script)
        self.assertIn("isMainHostSupervisionMirror", script)
        self.assertIn('sessionMenuEl?.classList.toggle("weixin-open", weixinConsoleOpen);', script)
        self.assertIn('target === "main"', script)
        self.assertIn('candidate.type !== "message"', script)
        self.assertNotIn("latestAgentMessage", script)
        self.assertIn('action === "add-task"', script)
        self.assertIn("task-dialog", styles)
        self.assertIn("task-create-trigger", styles)
        self.assertIn("task-supervision-editor", styles)
        self.assertIn("task-context-editor", styles)
        self.assertIn(".context-form", styles)
        self.assertIn("context-auto-on", styles)
        self.assertIn("agent-section", styles)
        self.assertIn("supervision-agents", styles)
        self.assertIn("agent-card.host-agent", styles)
        self.assertIn(".agent-backend-select", styles)
        self.assertIn(".session-menu.weixin-open", styles)
        self.assertIn("overflow: visible;", styles)
        self.assertIn(".session-menu.weixin-open .weixin-console-popover", styles)
        self.assertIn("right: calc(100% + 10px);", styles)
        self.assertIn("width: clamp(520px, calc(100vw - 430px), 680px);", styles)
        self.assertIn("position: fixed;", styles)
        self.assertIn("bottom: calc(12px + env(safe-area-inset-bottom));", styles)
        self.assertIn("max-height: none;", styles)
        self.assertNotIn("grid-template-areas:", styles)
        self.assertIn(".session-rename", styles)
        self.assertIn(".session-rename #rename-run-name", styles)
        self.assertIn(".session-create #new-run-goal", styles)
        self.assertIn("grid-template-columns: minmax(0, 1fr) minmax(0, 1fr) auto;", styles)
        self.assertIn("max-height: min(calc(var(--app-viewport-height) - 80px), 720px);", styles)
        self.assertIn("overflow-x: hidden;", styles)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr));", styles)
        self.assertIn(".agent-permissions select", styles)
        self.assertIn("width: 100%;", styles)
        self.assertIn("timeline-card.from-supervision", styles)

    def test_frontend_renders_host_work_log_in_host_view(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn("function agentTimelineEvents(taskId, target = backendTarget())", script)
        self.assertIn("conversationStates.get(conversationKey(taskId, target))", script)
        self.assertIn("agentTimelineEvents(taskId, target)", script)
        self.assertIn("conversationSourceEvents(taskId, target)", script)
        self.assertIn('target === "main" && isAhaActionEnvelopeText(text)', script)
        self.assertIn("function agentUpdateBody", script)
        self.assertIn("ahaActionEnvelopePayload(text)", script)
        self.assertIn("decision:", script)
        self.assertIn("response:", script)
        self.assertIn("actions:", script)
        self.assertIn("host update", script)

    def test_command_menu_floats_above_composer(self) -> None:
        root = Path(__file__).resolve().parents[1]
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertRegex(styles, r"\.workspace\s*\{[^}]*position: relative;")
        self.assertRegex(styles, r"\.command-menu\s*\{[^}]*position: absolute;[^}]*bottom: 62px;")
        self.assertRegex(styles, r"\.command-menu\s*\{[^}]*max-height: min\(42vh, 280px\);[^}]*overflow: auto;")
        self.assertIn("box-shadow: 0 -12px 28px rgba(15, 23, 42, 0.14);", styles)
        self.assertIn("bottom: calc(var(--mobile-composer-offset) + var(--mobile-keyboard-inset));", styles)

    def test_frontend_command_menu_only_lists_aha_final(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn('name: "/aha final"', script)
        self.assertNotIn('name: "/aha complete"', script)
        self.assertNotIn("Alias for /aha final", script)

    def test_frontend_has_weixin_console_entry(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "src" / "aha_cli" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="weixin-console"', html)
        self.assertIn('id="weixin-console-popover"', html)
        self.assertIn('aria-controls="weixin-console-popover"', html)
        self.assertIn("微信操作台", html)
        self.assertIn("const weixinConsoleEl", script)
        self.assertIn("const weixinConsolePopoverEl", script)
        self.assertIn("function setWeixinConsoleOpen", script)
        self.assertIn("function closeWeixinConsoleForOutsideEvent", script)
        self.assertIn('document.addEventListener("pointerdown", closeWeixinConsoleForOutsideEvent, true);', script)
        self.assertIn("function renderWeixinConsole", script)
        self.assertIn("function startWeixinPairing", script)
        self.assertIn("function resetWeixinPairing", script)
        self.assertIn("function sendWeixinTestNotification", script)
        self.assertIn("function setWeixinNotificationsEnabled", script)
        self.assertIn("const pairButtonDisabled = weixinState.loading || displayPaired;", script)
        self.assertIn("const sendContext = payload.send_context || {};", script)
        self.assertIn("会话可回复", script)
        self.assertIn("需微信发消息", script)
        self.assertIn("weixin-session-state", script)
        self.assertIn("const accountId = String(account.user_id || pairing.user_id || \"未配对\");", script)
        self.assertIn("class=\"weixin-account-id\"", script)
        self.assertIn('title="${escapeHtml(accountId)}"', script)
        self.assertIn('apiUrl("/api/weixin/pair")', script)
        self.assertIn('apiUrl("/api/weixin/reset")', script)
        self.assertIn('apiUrl("/api/weixin/test")', script)
        self.assertIn('apiUrl("/api/weixin/notifications")', script)
        self.assertIn("data-weixin-notifications-toggle", script)
        self.assertIn("微信通知", script)
        self.assertIn("微信配对二维码", script)
        self.assertIn("微信配对已重置", script)
        self.assertIn("发送测试通知", script)
        self.assertIn("最近接收消息", script)
        self.assertIn("receivedMessages", script)
        self.assertIn("weixin-received-list", script)
        self.assertIn("接收消息失败", script)
        self.assertNotIn('await activateTab("weixin");', script)
        self.assertNotIn('if (activeTab === "weixin") return;', script)
        self.assertNotIn("codex-weixin", script)
        self.assertNotIn("/home/kaikai/kk-workspace/my_project/codex-weixin", script)
        self.assertIn(".weixin-console", styles)
        self.assertIn(".weixin-console-popover", styles)
        self.assertIn(".weixin-console-grid", styles)
        self.assertIn(".weixin-notifications", styles)
        self.assertIn(".weixin-received", styles)
        self.assertIn(".weixin-received-list", styles)
        self.assertIn(".weixin-received-meta time", styles)
        self.assertIn(".weixin-console-grid code.weixin-account-id", styles)
        self.assertIn(".weixin-console-grid small", styles)
        self.assertIn(".weixin-console-grid code.weixin-session-state.warning", styles)
        self.assertIn("white-space: nowrap;", styles)
        self.assertIn("text-overflow: ellipsis;", styles)
        self.assertNotIn("const from = String(message?.from_user_id", script)
        self.assertIn("overflow-wrap: anywhere;", styles)
        self.assertIn("min-width: 0;", styles)
        self.assertIn(".weixin-qr", styles)
        self.assertIn(".weixin-test", styles)

    def test_frontend_renders_prompt_metrics_visualization(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("agent_prompt_metrics", script)
        self.assertIn("agent_context_overflow", script)
        self.assertIn("renderPromptMetricsPanel", script)
        self.assertIn("promptArtifactCache", script)
        self.assertIn("function renderRawPromptSection", script)
        self.assertIn("function ensurePromptArtifactLoaded", script)
        self.assertIn('apiUrl("/api/prompt-artifact", { ref })', script)
        self.assertIn("renderPanel({ preserveContextScroll: true })", script)
        self.assertIn("function captureContextScrollState", script)
        self.assertIn("function restoreContextScrollState", script)
        self.assertIn("rawPrompt.scrollTop", script)
        self.assertIn("panelEl.scrollTop = state.panelTop", script)
        self.assertIn("prompt_ref", script)
        self.assertIn("Latest assembled prompt", script)
        self.assertNotIn("Context snapshot / breakdown source", script)
        self.assertNotIn("context-snapshot-details", script)
        self.assertIn("loadConversationPage(selectedTaskId, backendTarget())", script)
        self.assertIn("AHA Input", script)
        self.assertIn("Backend Usage", script)
        self.assertIn("Backend Session", script)
        self.assertIn("Context Pressure", script)
        self.assertIn("contextPressureSummary", script)
        self.assertIn('if (pressure?.percent == null || pressure?.percent === "") return "";', script)
        self.assertNotIn("const percent = Number(pressure?.percent);", script)
        self.assertIn("function contextPressureHasPercent(pressure)", script)
        self.assertIn("function backendSessionId(session)", script)
        self.assertIn("function backendSessionIdsDiffer(nextSession, previousSession)", script)
        self.assertIn("function backendSessionWithPreviousContextPressure(nextSession, previousSession)", script)
        self.assertIn("if (backendSessionIdsDiffer(nextSession, previousSession)) return nextSession;", script)
        self.assertIn("return { ...nextSession, context_pressure: previousSession.context_pressure };", script)
        self.assertIn("state.backendSession = backendSessionWithPreviousContextPressure(payload.backend_session, state.backendSession);", script)
        self.assertNotIn("state.backendSession = null;", script)
        self.assertIn("const contextPercent = contextPressurePercent(contextPressure);", script)
        self.assertIn("const contextHeadline = contextPercent ? `${contextPercent} context` : \"context unknown\";", script)
        self.assertIn("const contextInputTokens = contextPressure?.input_tokens ?? contextPressure?.prompt_tokens;", script)
        self.assertIn("const contextWindowTokens = contextPressure?.context_window;", script)
        self.assertIn("const contextWindowUsedLabel = contextInputTokens != null ? `window used ${formatMetricCompact(contextInputTokens)}` : \"\";", script)
        self.assertIn("const contextWindowTotalLabel = contextWindowTokens != null ? `window total ${formatMetricCompact(contextWindowTokens)}` : \"\";", script)
        self.assertIn("const contextWindowUsedTotalLabel = contextInputTokens != null && contextWindowTokens != null", script)
        self.assertIn("window used ${formatMetricCompact(contextInputTokens)} / total ${formatMetricCompact(contextWindowTokens)}", script)
        self.assertIn('class="status ${contextStatus.className}"', script)
        self.assertIn("context-metrics-section", script)
        self.assertNotIn('class="status ${displayedSessionStatus.className}"', script)
        self.assertIn("contextPressurePercent(metrics.contextPressure)", script)
        self.assertIn("triggerContextStatus", script)
        self.assertIn("Context ${summary}; Session", script)
        self.assertIn("ctx ?", script)
        self.assertIn("backend_context_pressure", script)
        self.assertIn("runtime_input_tokens", script)
        self.assertIn("runtime_cached_input_tokens", script)
        self.assertIn("input tokens", script)
        self.assertIn("prompt_tokens", script)
        self.assertIn("prompt_chars", script)
        self.assertIn("pressure_source", script)
        self.assertIn("/aha session compact-reset", script)
        self.assertIn("compactResetStates", script)
        self.assertIn("Compacting", script)
        self.assertIn("Restarting", script)
        self.assertIn("COMPACT_RESET_TIMEOUT_MS", script)
        self.assertIn("Checking", script)
        self.assertIn("verifyCompactResetAfterTimeout", script)
        self.assertIn("isRequestTimeoutError", script)
        self.assertIn("compactResetSelectedSession", script)
        self.assertIn("invalidateConversationBackendSession", script)
        self.assertIn('event.type === "backend_session_compact_reset"', script)
        self.assertIn("backendSessionRefreshEventTypes", script)
        self.assertIn('backendSessionRefreshEventTypes.has(event.type)', script)
        self.assertIn('"agent_started"', script)
        self.assertIn('"backend_started"', script)
        self.assertIn('"backend_session_reset"', script)
        self.assertIn('"backend_session_compact_reset"', script)
        self.assertIn("queueConversationBackendSessionRefresh", script)
        self.assertIn("isCurrentConversationTarget(taskId, target)", script)
        self.assertIn('"metrics-event"', script)
        self.assertIn('"session-reset", { invalidate: true }', script)
        self.assertIn('"compact-reset", { invalidate: true }', script)
        self.assertIn("refreshConversationBackendSession(taskId, target, { render: true", script)
        self.assertIn("CONVERSATION_SESSION_REFRESH_FALLBACK_MS", script)
        self.assertIn("maybeRefreshConversationBackendSessionFallback", script)
        self.assertIn("conversationSessionRefreshAt", script)
        self.assertIn("loadConversationPage(taskId, target, false, true)", script)
        self.assertIn("capturePromptMetricsPopoverState", script)
        self.assertIn("restorePromptMetricsPopoverState(metricsPopoverState)", script)
        self.assertIn("popoverScrollTop", script)
        self.assertIn("ahaInputMetricsStatus", script)
        self.assertIn("backendSessionStatus", script)
        self.assertIn("BACKEND_SESSION_WATCH_BYTES", script)
        self.assertIn("BACKEND_SESSION_COMPACT_BYTES", script)
        self.assertIn("Compact & Reset", script)
        self.assertIn("compactResetAdvice", script)
        self.assertIn("compact-metrics-details", script)
        self.assertIn("sessionAhaCounts", script)
        self.assertIn("Session breakdown", script)
        self.assertIn("renderSessionBreakdown", script)
        self.assertIn("AHA input breakdown", script)
        self.assertIn("Backend usage breakdown", script)
        self.assertIn("closePromptMetricsBreakdowns", script)
        self.assertIn("sessionBreakdownOpen", script)
        self.assertIn("breakdownOpen", script)
        self.assertIn("cache_read_input_tokens", script)
        self.assertIn("cache_creation_input_tokens", script)
        self.assertIn("total_cost_usd", script)
        self.assertIn("usageMetricsStatus", script)
        self.assertIn("prompt-component-bars", script)
        self.assertIn("backend-metrics-section", styles)
        self.assertIn("context-metrics-section", styles)
        self.assertIn("raw-prompt-section", styles)
        self.assertIn("raw-prompt-body", styles)
        self.assertNotIn("context-snapshot-details", styles)
        self.assertIn(".context-metrics-section .prompt-metrics-head > div:first-child > strong", styles)
        self.assertIn(".context-metrics-section .prompt-metrics-head > div:first-child > code", styles)
        self.assertIn("session-metrics-section", styles)
        self.assertIn("prompt-current", styles)
        self.assertIn("prompt-latest", styles)
        self.assertIn("session-large", styles)
        self.assertIn("session-watch", styles)
        self.assertIn("session-overflow", styles)
        self.assertIn("session-pending", styles)
        self.assertIn("session-done", styles)
        self.assertIn("compact-reset-primary", styles)
        self.assertIn("compact-metrics-detail-grid", styles)
        self.assertIn("prompt-metrics-head-actions", styles)
        self.assertIn("session-breakdown-row", styles)
        self.assertIn("metrics-breakdown-row-wide", styles)
        self.assertIn("usage-previous", styles)
        self.assertIn("context-watch", styles)
        self.assertIn("context-high", styles)
        self.assertIn(".turn-metrics.context-ok", styles)
        self.assertIn(".turn-metrics.context-watch", styles)
        self.assertIn(".turn-metrics.context-high", styles)
        self.assertIn(".turn-metrics.context-unknown", styles)
        self.assertIn("session-ok", styles)
        self.assertIn("prompt-metrics", styles)
        self.assertIn("prompt-component-track", styles)

    def test_frontend_does_not_inherit_context_pressure_across_backend_sessions(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn('return String(session?.id || session?.backend_session_id || "").trim();', script)
        self.assertIn("return Boolean(nextId || previousId) && nextId !== previousId;", script)
        self.assertIn("if (backendSessionIdsDiffer(nextSession, previousSession)) return nextSession;", script)

    def test_conversation_show_filter_only_renders_on_conversation_tab(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('conversationFiltersEl.classList.toggle("hidden", activeTab !== "conversation");', script)
        self.assertIn('if (activeTab !== "conversation") return;', script)
        filter_rule_index = styles.find(".conversation-filters {\n  display: flex;")
        hidden_rule_index = styles.find(".conversation-filters.hidden { display: none; }")
        self.assertGreaterEqual(filter_rule_index, 0)
        self.assertGreater(hidden_rule_index, filter_rule_index)

    def test_frontend_keeps_supervision_state_in_runtime_filter(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertNotIn('supervisionEventTypes.has(event.type)) return "chat"', script)
        self.assertIn('if (event.type === "message") return "chat";', script)
        self.assertIn('if (event.type === "host_decision") return renderTimelineStatus("host decision"', script)

    def test_frontend_prefills_empty_proxy_inputs_from_defaults(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertNotIn("taskAgentInputPrompt", script)
        self.assertNotIn("fillTaskAgentPromptFromHint", script)
        self.assertIn('const defaultHttpProxy = "http://127.0.0.1:7890";', script)
        self.assertIn("function applyProxyDefaultValues", script)
        self.assertIn("function fillTaskCreateProxyDefaults", script)
        self.assertIn("function fillSelectedTaskProxyDefaults", script)
        self.assertNotIn("function fillBootstrapProxyDefaults", script)
        self.assertIn('input?.addEventListener("focus", fillSelectedTaskProxyDefaults);', script)
        self.assertIn('input?.addEventListener("click", fillTaskCreateProxyDefaults);', script)
        self.assertNotIn('data-bootstrap-http-proxy', script)

    def test_frontend_remembers_selected_task_and_selects_created_task(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn('queryParams.get("selected_task_id")', script)
        self.assertIn("const initialSelectedTaskId", script)
        self.assertIn("let selectedTaskId = initialSelectedTaskId || null;", script)
        self.assertIn("function selectedTaskStorageKey", script)
        self.assertIn("function readStoredSelectedTaskId", script)
        self.assertIn("function writeStoredSelectedTaskId", script)
        self.assertIn("if (!initialSelectedTaskId) selectedTaskId = readStoredSelectedTaskId() || selectedTaskId;", script)
        self.assertIn("selectedTaskId = readStoredSelectedTaskId() || null;", script)
        self.assertIn("writeStoredSelectedTaskId(selectedTaskId);", script)
        self.assertIn("writeStoredSelectedTaskId(taskId);", script)
        self.assertIn("const createdTaskId = String(response?.task?.id || \"\").trim();", script)
        self.assertIn("if (createdTaskId) await selectTask(createdTaskId);", script)

    def test_frontend_keeps_turn_events_realtime_with_chat_only_filter(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("const conversationPageLimit = 30;", script)
        self.assertIn("const turnEventTypes = new Set", script)
        self.assertIn('"agent_started"', script)
        self.assertIn("conversationFilters[conversationEventCategory(event)] || turnEventTypes.has(event.type)", script)
        self.assertIn("Agent is idle", script)
        self.assertIn("function agentWaitingReason(agent)", script)
        self.assertIn("Agent is waiting for host", script)
        self.assertIn("waiting_reason", script)
        self.assertIn("waiting ${timing.waitingReason}", script)
        self.assertIn("const timer = renderTurnTimer(taskId);", script)
        self.assertIn('const visualStatus = timing.running && !["waiting", "busy"].includes(timing.status) ? "running" : timing.status;', script)
        self.assertIn('class="turn-timer ${escapeHtml(visualStatus)}"', script)
        self.assertIn("`status ${timing.status}`", script)
        self.assertIn(".turn-timer.idle", styles)
        self.assertIn(".turn-timer.running .activity-dot,\n.turn-timer.waiting .activity-dot,\n.turn-timer.pending .activity-dot", styles)
        self.assertIn("box-shadow: 0 0 0 4px #dcfce7;", styles)
        self.assertIn(".turn-timer.busy .activity-dot", styles)
        self.assertIn("box-shadow: 0 0 0 4px #fef3c7;", styles)
        self.assertIn("taskAgentCount(task)", script)
        self.assertIn('url.searchParams.set("lite", "1")', script)
        self.assertIn('url.searchParams.set("selected_task_id", selectedTaskId)', script)

        self.assertIn("selectedTaskNeedsAgentDetails", script)
        self.assertIn("applyBackendData(payload.backends || [])", script)
        self.assertNotIn("Promise.all([loadBackends(), loadWorkspaces()])", script)

    def test_frontend_keeps_conversation_scroll_and_expansion_stable(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn('data-load-older="true"', script)
        self.assertIn("if (button) loadOlderConversation();", script)
        self.assertNotIn("if (panelEl.scrollTop < 48) loadOlderConversation();", script)
        self.assertIn("function expandedMessageStateKey", script)
        self.assertIn("function syncExpandedMessageKeysFromDom", script)
        self.assertIn("syncExpandedMessageKeysFromDom();", script)
        self.assertIn("data-message-context-key", script)
        self.assertIn("expandedMessageKeys.has(expandedMessageStateKey(key, contextKey))", script)
        self.assertIn('event.target.closest(".collapsed-message > summary")', script)
        self.assertIn("setExpandedMessageKey(details.dataset.messageKey, !details.open, details.dataset.messageContextKey);", script)
        self.assertIn("setExpandedMessageKey(key, details.open, details.dataset.messageContextKey);", script)

    def test_frontend_pending_messages_wait_for_agent_blockers(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn("function agentInputWaitBlocked(agent)", script)
        self.assertIn('reason === "subagents" || reason === "host"', script)
        self.assertIn("function taskHostInputBlocked(task)", script)
        self.assertIn('return status === "pending" || status === "running" || status === "waiting";', script)
        self.assertIn("function selectedAgentInputBlocked()", script)
        self.assertIn("return selectedBackendActive() || agentInputWaitBlocked(selectedAgent()) || taskHostInputBlocked(selectedTask());", script)
        self.assertIn("if (!task || selectedAgentInputBlocked()) return null;", script)
        self.assertIn("if (selectedAgentInputBlocked() && !isAha)", script)
        self.assertIn("if (response?.deferred)", script)
        self.assertIn("if (currentMessage) addPendingMessage(currentMessage, task, target);", script)
        self.assertIn("Agent 忙碌或等待中收到的消息会先暂存", script)

    def test_frontend_adjusts_mobile_viewport_for_keyboard(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "src" / "aha_cli" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("interactive-widget=overlays-content", html)
        self.assertIn("initMobileViewport", script)
        self.assertIn("window.visualViewport", script)
        self.assertIn("navigator.virtualKeyboard", script)
        self.assertIn("keepMobileControlVisible", script)
        self.assertIn("mobileDialogScrollerFor", script)
        self.assertNotIn('style.setProperty("--app-viewport-height"', script)
        self.assertIn("--mobile-keyboard-inset", script)
        self.assertIn("mobile-keyboard-active", script)
        self.assertIn('document.addEventListener("focusin"', script)
        self.assertIn('document.addEventListener("focusout"', script)
        self.assertIn("--app-viewport-height", styles)
        self.assertIn("--mobile-keyboard-inset", styles)
        self.assertIn("height: var(--app-viewport-height)", styles)
        self.assertIn("translate3d(0, calc(-1 * var(--mobile-keyboard-inset)), 0)", styles)
        self.assertIn("body.mobile-keyboard-active .composer", styles)
        self.assertIn("body.mobile-keyboard-active .task-dialog-panel", styles)
        self.assertIn("body.mobile-keyboard-active .task-dialog-actions", styles)
