from __future__ import annotations

from pathlib import Path
import unittest


class FrontendStaticTests(unittest.TestCase):
    def test_frontend_prefers_websocket_with_cursor_and_polling_fallback(self) -> None:
        script_path = Path(__file__).resolve().parents[1] / "src" / "aha_cli" / "web" / "static" / "app.js"
        script = script_path.read_text(encoding="utf-8")
        websocket_index = script.find("new WebSocket")

        self.assertGreaterEqual(websocket_index, 0, "frontend should open a WebSocket transport")
        websocket_block = script[max(0, websocket_index - 2000) : websocket_index + 3000]
        self.assertRegex(script, r"last_event_id|after_event_id")
        self.assertRegex(websocket_block, r"onclose|onerror|catch")
        self.assertIn("pollEvents", script)
        self.assertIn("catchUpRealtimeEvents", script)
        self.assertIn("forcePoll", script)
        self.assertIn("allowStalePoll", script)
        self.assertIn("lastRealtimeMessageAt", script)
        self.assertIn("eventSocketStaleMs", script)
        self.assertIn("closeStaleEventWebSocket", script)
        self.assertIn("ws.stale_close", script)
        self.assertIn("visibilitychange", script)
        self.assertIn('"online"', script)
        self.assertRegex(script, r"typeof\s+WebSocket|WebSocket\s+in\s+window|window\.WebSocket")

    def test_frontend_uses_bootstrap_for_empty_state(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("/api/bootstrap", script)
        self.assertIn("renderFirstRunState", script)
        self.assertIn("data-bootstrap-run-form", script)
        self.assertIn("createRunFromBootstrapForm", script)
        self.assertIn("data-bootstrap-collaboration-mode", script)
        self.assertIn("data-bootstrap-collaboration-help", script)
        self.assertIn("data-bootstrap-proxy-enabled", script)
        self.assertIn("data-bootstrap-http-proxy", script)
        self.assertIn("data-bootstrap-https-proxy", script)
        self.assertIn("data-bootstrap-no-proxy", script)
        self.assertIn("Start Run and Initial Task", script)
        self.assertIn("renderBootstrapError", script)
        self.assertIn("new-run-collaboration", script)
        self.assertIn("new-run-collaboration-help", script)
        self.assertIn("collaborationMode: newRunCollaborationEl?.value", script)
        self.assertIn("syncNewRunCollaborationHelp", script)
        self.assertIn("syncBootstrapCollaborationHelp", script)
        self.assertIn("body.empty-run .sidebar", styles)
        self.assertIn("bootstrap-panel", styles)
        self.assertIn("bootstrap-proxy", styles)
        self.assertIn("collaboration-help", styles)

    def test_frontend_uses_modal_for_task_create(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "src" / "aha_cli" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("open-task-create", html)
        self.assertIn("task-create-dialog", html)
        self.assertIn("new-task-description", html)
        self.assertIn('form id="task-form"', html)
        self.assertIn("task-supervision-editor", html)
        self.assertIn("collaboration-mode", html)
        self.assertIn("collaboration-mode-help", html)
        self.assertIn("只限制 auto 模式下最多能启用几个 sub-agent", html)
        self.assertIn("selected-task-supervision-mode", html)
        self.assertIn("task-supervision-mode", html)
        self.assertIn("task-supervision-max-rounds", html)
        self.assertIn("task-supervision-ask-user-gates", html)
        self.assertIn("selected-task-supervision-ask-user-gates", html)
        self.assertIn("assisted Codex host", html)
        self.assertIn("assisted Claude host", html)
        self.assertNotIn("selected-task-supervision-actions", html)
        create_form = html.split('<form id="task-form"', 1)[1].split("</form>", 1)[0]
        self.assertIn("task-supervision-mode", create_form)
        self.assertNotIn("selected-task-supervision-mode", create_form)
        self.assertIn("openTaskCreateDialog", script)
        self.assertIn("closeTaskCreateDialog", script)
        self.assertIn("saveTaskSupervisionConfig", script)
        self.assertIn("taskSupervisionPayloadFromMode", script)
        self.assertIn("collaboration_mode", script)
        self.assertIn("taskCollaborationSummary", script)
        self.assertIn("syncCollaborationFields", script)
        self.assertIn("collaborationModeDescriptions", script)
        self.assertIn("AHA 会在能提速时自动组队", script)
        self.assertIn("supervisionAskUserGateDefs", script)
        self.assertIn("ask_user_gates", script)
        self.assertIn("readAskUserGateControls", script)
        self.assertIn("syncCreateTaskSupervisionModeFields", script)
        self.assertIn("assisted_codex", script)
        self.assertIn('policy.mode === "manual"', script)
        self.assertIn('"host / user proxy"', script)
        self.assertIn("isSupervisionAgent", script)
        self.assertIn("Main & sub agents", script)
        self.assertIn("Supervision", script)
        self.assertIn("agent-section", script)
        self.assertIn("data-agent-id", script)
        self.assertIn("host-agent", script)
        self.assertIn("display_sender", script)
        self.assertIn("from-supervision", script)
        self.assertIn("consumedAgentMessages", script)
        self.assertIn("mirroredMainBrowserMessages", script)
        self.assertIn("isMainHostSupervisionMirror", script)
        self.assertIn('backendTarget() === "main"', script)
        self.assertIn('candidate.type !== "message"', script)
        self.assertNotIn("latestAgentMessage", script)
        self.assertIn('action === "add-task"', script)
        self.assertIn("task-dialog", styles)
        self.assertIn("task-create-trigger", styles)
        self.assertIn("task-supervision-editor", styles)
        self.assertIn("agent-section", styles)
        self.assertIn("supervision-agents", styles)
        self.assertIn("agent-card.host-agent", styles)
        self.assertIn("timeline-card.from-supervision", styles)

    def test_frontend_renders_prompt_metrics_visualization(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("agent_prompt_metrics", script)
        self.assertIn("agent_context_overflow", script)
        self.assertIn("renderPromptMetricsPanel", script)
        self.assertIn("AHA Input", script)
        self.assertIn("Backend Usage", script)
        self.assertIn("Backend Session", script)
        self.assertIn("/aha session compact-reset", script)
        self.assertIn("compactResetStates", script)
        self.assertIn("Compacting", script)
        self.assertIn("Restarting", script)
        self.assertIn("COMPACT_RESET_TIMEOUT_MS", script)
        self.assertIn("Checking", script)
        self.assertIn("verifyCompactResetAfterTimeout", script)
        self.assertIn("isRequestTimeoutError", script)
        self.assertIn("compactResetSelectedSession", script)
        self.assertIn("ahaInputMetricsStatus", script)
        self.assertIn("backendSessionStatus", script)
        self.assertIn("BACKEND_SESSION_LARGE_BYTES", script)
        self.assertIn("sessionAhaCounts", script)
        self.assertIn("Session breakdown", script)
        self.assertIn("renderSessionBreakdown", script)
        self.assertIn("AHA input breakdown", script)
        self.assertIn("Backend usage breakdown", script)
        self.assertIn("closePromptMetricsBreakdowns", script)
        self.assertIn("sessionBreakdownOpen", script)
        self.assertIn("breakdownOpen", script)
        self.assertIn("cache_read_input_tokens", script)
        self.assertIn("cache_creation_input_tokens", script)
        self.assertIn("total_cost_usd", script)
        self.assertIn("usageMetricsStatus", script)
        self.assertIn("prompt-component-bars", script)
        self.assertIn("backend-metrics-section", styles)
        self.assertIn("session-metrics-section", styles)
        self.assertIn("prompt-current", styles)
        self.assertIn("prompt-latest", styles)
        self.assertIn("session-large", styles)
        self.assertIn("session-overflow", styles)
        self.assertIn("session-pending", styles)
        self.assertIn("session-done", styles)
        self.assertIn("prompt-metrics-head-actions", styles)
        self.assertIn("session-breakdown-row", styles)
        self.assertIn("metrics-breakdown-row-wide", styles)
        self.assertIn("usage-previous", styles)
        self.assertIn("session-ok", styles)
        self.assertIn("prompt-metrics", styles)
        self.assertIn("prompt-component-track", styles)

    def test_frontend_keeps_supervision_state_in_runtime_filter(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertNotIn('supervisionEventTypes.has(event.type)) return "chat"', script)
        self.assertIn('if (event.type === "message") return "chat";', script)
        self.assertIn('if (event.type === "host_decision") return renderTimelineStatus("host decision"', script)

    def test_frontend_prefills_empty_task_agent_composer_from_prompt_hint(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn("function taskAgentInputPrompt", script)
        self.assertIn("function fillTaskAgentPromptFromHint", script)
        self.assertIn("if (!messageEl || messageEl.value.trim()) return false;", script)
        self.assertIn("继续处理任务：", script)
        self.assertIn("任务说明：", script)
        self.assertIn('messageEl.addEventListener("focus", () => {', script)
        self.assertIn("if (fillTaskAgentPromptFromHint()) return;", script)
        self.assertIn('messageEl.addEventListener("click", () => {', script)

    def test_frontend_remembers_selected_task_and_selects_created_task(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn('queryParams.get("selected_task_id")', script)
        self.assertIn("function selectedTaskStorageKey", script)
        self.assertIn("function readStoredSelectedTaskId", script)
        self.assertIn("function writeStoredSelectedTaskId", script)
        self.assertIn("selectedTaskId = readStoredSelectedTaskId() || null;", script)
        self.assertIn("writeStoredSelectedTaskId(selectedTaskId);", script)
        self.assertIn("writeStoredSelectedTaskId(taskId);", script)
        self.assertIn("const createdTaskId = String(response?.task?.id || \"\").trim();", script)
        self.assertIn("if (createdTaskId) await selectTask(createdTaskId);", script)

    def test_frontend_keeps_turn_events_realtime_with_chat_only_filter(self) -> None:
        root = Path(__file__).resolve().parents[1]
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("const conversationPageLimit = 30;", script)
        self.assertIn("const turnEventTypes = new Set", script)
        self.assertIn('"agent_started"', script)
        self.assertIn("conversationFilters[conversationEventCategory(event)] || turnEventTypes.has(event.type)", script)
        self.assertIn("Agent is idle", script)
        self.assertIn("const timer = renderTurnTimer(taskId);", script)
        self.assertIn(".turn-timer.idle", styles)
        self.assertIn("taskAgentCount(task)", script)
        self.assertIn('url.searchParams.set("lite", "1")', script)
        self.assertIn('url.searchParams.set("selected_task_id", selectedTaskId)', script)
        self.assertIn("selectedTaskNeedsAgentDetails", script)
        self.assertIn("applyBackendData(payload.backends || [])", script)
        self.assertNotIn("Promise.all([loadBackends(), loadWorkspaces()])", script)

    def test_frontend_adjusts_mobile_viewport_for_keyboard(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "src" / "aha_cli" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        script = (root / "src" / "aha_cli" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (root / "src" / "aha_cli" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("interactive-widget=overlays-content", html)
        self.assertIn("initMobileViewport", script)
        self.assertIn("window.visualViewport", script)
        self.assertIn("navigator.virtualKeyboard", script)
        self.assertIn("keepMobileControlVisible", script)
        self.assertIn("mobileDialogScrollerFor", script)
        self.assertNotIn('style.setProperty("--app-viewport-height"', script)
        self.assertIn("--mobile-keyboard-inset", script)
        self.assertIn("mobile-keyboard-active", script)
        self.assertIn('document.addEventListener("focusin"', script)
        self.assertIn('document.addEventListener("focusout"', script)
        self.assertIn("--app-viewport-height", styles)
        self.assertIn("--mobile-keyboard-inset", styles)
        self.assertIn("height: var(--app-viewport-height)", styles)
        self.assertIn("translate3d(0, calc(-1 * var(--mobile-keyboard-inset)), 0)", styles)
        self.assertIn("body.mobile-keyboard-active .composer", styles)
        self.assertIn("body.mobile-keyboard-active .task-dialog-panel", styles)
        self.assertIn("body.mobile-keyboard-active .task-dialog-actions", styles)
